name: Build and Push Docker Image
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          TAG=${GITHUB_REF##*/}
          docker buildx build --push \
          -t ${REGISTRY}/confd:${TAG} \
          --build-arg VERSION=${TAG} \
          --platform linux/amd64,linux/arm64 \
          -f ./Dockerfile .

          # export for upload
          docker buildx build \
          -t ${REGISTRY}/confd:${TAG} \
          --build-arg VERSION=${TAG} \
          --platform linux/amd64 \
          --output type=docker,dest=./image.tar \
          -f ./Dockerfile .

          gzip image.tar

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: confd-image.tar.gz
          path: |
            image.tar.gz
          retention-days: 5

      - name: Push to COS
        if: startsWith(github.ref, 'refs/tags/')
        env:
          SECRET_ID: ${{ secrets.QCLOUD_COS_SECRETID }}
          SECRET_KEY: ${{ secrets.QCLOUD_COS_SECRETKEY }}
          BUCKET: api7-enterprise-1301662268
          ENDPOINT: cos.accelerate.myqcloud.com
        run: |
          TAG=${GITHUB_REF##*/}
          sudo pip install coscmd
          coscmd config -a ${SECRET_ID} -s ${SECRET_KEY} -b ${BUCKET} -e ${ENDPOINT}
          coscmd upload image.tar.gz  /workflows/images/confd-${TAG}.tar.gz  
