name: Build and Push Docker Image
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build and Push
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          TAG=${GITHUB_REF##*/}
          docker buildx build -o type=local,dest=./ \
          -t confd:${TAG} \
          --platform linux/amd64,linux/arm64 \
          -f ./Dockerfile .

      - name: Build arm64 Image and push to Docker Registry
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          GOOS: "linux"
          GOARCH: "arm64"
        run: |
          make build-image-local
          docker tag api7/confd:dev confd:${{ steps.branch_env.outputs.version }}-arm64
          docker save confd:${{ steps.branch_env.outputs.version }}-arm64 | gzip > confd.tar.gz

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: image-confd-arm64.tar
          path: |
            ./confd.tar.gz
          retention-days: 1
