name: Integration Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-test:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: quay.io/coreos/etcd
        ports:
          - 2379:2379
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build and Install
        run: |
          go install  go.etcd.io/etcd/etcdctl/v3

      - name: Build and Install
        run: |
          make build
          sudo make install

      - name: Wait for etcd ready
        run: |
          wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- localhost:2379 -- echo "etcd is up"

      - name: Test with etcd
        run: |
          integration/etcdv3/test.sh
          integration/expect/check.sh
